version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URL: mongodb
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:4
